### ISSUE TITLE
AttributeError: 'C' object has no attribute 'projname' when running run_mcflirt.py

### ISSUE THREAD

**Issue by shuo-zhou** [poldrack/openfmri#14]
'C' object in 'launch_qsub.py' do not have the parameters of 'projname', 'hold' and 'directory'. Is there some actions other than the process introduced at https://openfmri.org/data-processing-stream/ to be done?

**Comment by poldrack** [comment]
hi - this code is no longer being supported.  please see https://github.com/poldracklab/fmriprep
