### ISSUE TITLE
ds000201 -- missing , after a name in dataset_description.json

### ISSUE THREAD

**Issue by yarikoptic** [poldrack/openfmri#6]
thought it was again utf8 stricking back but it is just a banal missing comma (after Peter's name).  since @vsoch liked my screen shots so much, here it is:
![screenshot](http://www.onerussian.com/tmp/gkrellShoot_08-29-16_190055.png)

**Comment by vsoch** [comment]
+1! :hamburger: 

Yes, simple validation of the files should take care of this - we do something similar for experiment factory, the [validation function](https://github.com/expfactory/expfactory-python/blob/master/expfactory/experiment.py#L90) first tries loading the json file, and returns invalid if it doesn't work. It's surprised me how often and easy it is to forget commas, quotes, and the like.

**Comment by yarikoptic** [comment]
I think this one is fixed but caused #9 ;)
